### ISSUE TITLE
download error while setting up dbs...

### ISSUE THREAD

**Issue by telatin** [raw-lab/MetaCerberus#15] opened 2024-04-04 12:59 UTC
Hi there, thanks for this tool!
I tried downloading the dbs with `metacerberus.py --setup` and got:

```bash
Downloading Database files to /usr/users/QIB_fr009/telatina/micromamba/envs/metacerberus/lib/python3.10/site-packages/meta_cerberus/DB
This will take a few minutes...
Downloading CAZy
Downloading COG
Downloading PHROG
Downloading VOG
Downloading KOFam
Traceback (most recent call last):
  File "/usr/users/QIB_fr009/telatina/micromamba/envs/metacerberus/bin/metacerberus.py", line 857, in <module>
    sys.exit(main())
  File "/usr/users/QIB_fr009/telatina/micromamba/envs/metacerberus/bin/metacerberus.py", line 192, in main
    metacerberus_setup.Download(pathDB)
  File "/usr/users/QIB_fr009/telatina/micromamba/envs/metacerberus/lib/python3.10/site-packages/meta_cerberus/metacerberus_setup.py", line 79, in Download
    url.urlretrieve("https://osf.io/gk7vx/download", os.path.join(pathDB, "KOFam_eukaryote.hmm.gz"))
  File "/usr/users/QIB_fr009/telatina/micromamba/envs/metacerberus/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/users/QIB_fr009/telatina/micromamba/envs/metacerberus/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/users/QIB_fr009/telatina/micromamba/envs/metacerberus/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/users/QIB_fr009/telatina/micromamba/envs/metacerberus/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/users/QIB_fr009/telatina/micromamba/envs/metacerberus/lib/python3.10/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
  File "/usr/users/QIB_fr009/telatina/micromamba/envs/metacerberus/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/users/QIB_fr009/telatina/micromamba/envs/metacerberus/lib/python3.10/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/users/QIB_fr009/telatina/micromamba/envs/metacerberus/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/users/QIB_fr009/telatina/micromamba/envs/metacerberus/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/users/QIB_fr009/telatina/micromamba/envs/metacerberus/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/users/QIB_fr009/telatina/micromamba/envs/metacerberus/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/users/QIB_fr009/telatina/micromamba/envs/metacerberus/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

```

I assume the error is with the last db (`KOFam`), I just report this in case it could make sense to download the available dbs and just report those who couldn't be downloaded, or just report errors in a different way

**Comment by decrevi** [comment] 2024-04-04 16:34
Hello, thank you for your feedback.

I am working on fixing this up with the next release. The next version will also be able to download individual databases, so if one fails it doesn't force a download of all of them again.

It seems to me that this error was caused by a network issue not related to MetaCerberus, since the link it failed on is working (https://osf.io/gk7vx/download)

I will make sure that error messages here are more informative.

**Comment by telatin** [comment] 2024-04-04 16:38
Yes I just re-run it and worked. I meant exactly what you said about
exception handling and of course allowing for individual db download is
also nice.
Thanks

**Comment by raw-lab** [comment] 2024-04-12 20:16
Thank you for using MetaCerberus. We will add the individual db download in version 1.3. 
If there are other databases or custom databases we can add for your needs please let us know?
We are going to close this for now.

**Closed as completed by raw-lab** 2024-04-12 20:16 UTC
